### ISSUE TITLE
Error: [R: compile error] Error: spawnSync C:\WINDOWS\system32\cmd.exe ENOBUFS

### ISSUE THREAD

**Issue by pabloat81** [FabrizioSandri/r-integration#13] opened 2022-09-30 13:33 UTC
Hello, it is possible to increase buffer size?

thanks

**Comment by FabrizioSandri** [comment] 2022-10-20 20:16
Hello, @pabloat81. Could you please expand on what you mean by buffer size? 

It appears that the issue you are experiencing is tied to a Windows system. Could you please tell me how to replicate this issue?

**Comment by pabloat81** [comment] 2022-10-20 20:31
Hi,

I get this error when excecuting a R script with a large CSV file. I have to make some joins, group and nest. when excecute a nest() command i get this error.

Example of my R code (i changed the nest() commnad and i am generating the json file in another form).

x <- detalles %>%
  group_by(numero) %>%
  nest()

cd <- merge(cd, x, by = "numero")
p <- pagos %>%
  group_by(numero) %>%
  nest()

cdp <- merge(cd, p, by = "numero")

names(cdp)[names(cdp) == "data"] <- "pagos"

json <- toJSON(cdp, pretty = FALSE)

**Comment by FabrizioSandri** [comment] 2022-11-03 07:38
Hi! The problem is caused by the `child_process.exec()` function, which truncates script output if it exceeds 1024*1024 bytes 

This should be fixed in [Release 2.5.0](https://github.com/FabrizioSandri/r-integration/releases/tag/v2.5.0)

**Closed by FabrizioSandri** 2022-11-03 07:38 UTC
